//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesTenis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestenis_defEntities : DbContext
    {
        public gestenis_defEntities()
            : base("name=gestenis_defEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<recursos> recursos { get; set; }
        public virtual DbSet<reservas> reservas { get; set; }
        public virtual DbSet<socios> socios { get; set; }
    }
}
