//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesTenis
{
    using System;
    using System.Collections.Generic;
    
    public partial class recursos
    {
        public recursos()
        {
            this.reservas = new HashSet<reservas>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public System.DateTime f_alta { get; set; }
        public Nullable<System.DateTime> f_baja { get; set; }
        public string nombre_rec { get; set; }
        public string superficie { get; set; }
        public bool disponible { get; set; }
    
        public virtual ICollection<reservas> reservas { get; set; }
    }
}
