//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesTenis
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservas
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public byte hora { get; set; }
        public bool pagado { get; set; }
        public double precio { get; set; }
    
        public virtual facturas facturas { get; set; }
        public virtual recursos recursos { get; set; }
        public virtual socios socios { get; set; }
    }
}
